from synthesis_paragraph_classifier.featurizers.SentenceHighFreqTopics import SentenceHighFreqTopics
from synthesis_paragraph_classifier.featurizers.TopicNGram import SentenceTopicBiGram, SentenceTopicTriGram
